AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for twitter-screenshot

Resources:
  ScreenshotFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        TakeScreenshot:
          Type: Api
          Properties:
            Path: /screenshot
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./app
      DockerTag: python3.9-v1

Outputs:
  TwitterScreenshotApi:
    Description: "API Gateway URL for prod stage of screenshot function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/screenshot/"
  ScreenshotFunction:
    Description: "Screenshot Lambda Function ARN"
    Value: !GetAtt ScreenshotFunction.Arn
  ScreenshotFunctionIAMRole:
    Description: "Implicit IAM Role created for Screenshot function"
    Value: !GetAtt ScreenshotFunction.Arn
