AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for twitter-screenshot

Resources:
  ScreenshotApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      BinaryMediaTypes: ["*/*"]
  ScreenshotFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 1024
      Timeout: 303
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        TakeScreenshot:
          Type: Api
          Properties:
            Path: /screenshot/{tweet_url}
            Method: get
            RestApiId:
              Ref: ScreenshotApi
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./app
      DockerTag: python3.9-v1

Outputs:
  TwitterScreenshotApi:
    Description: "API Gateway URL for prod stage of screenshot function"
    Value: !Sub "https://${ScreenshotApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/screenshot/"
  ScreenshotFunction:
    Description: "Screenshot Lambda Function ARN"
    Value: !GetAtt ScreenshotFunction.Arn
  ScreenshotFunctionIAMRole:
    Description: "Implicit IAM Role created for Screenshot function"
    Value: !GetAtt ScreenshotFunction.Arn
